package DistributedTest.patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'DistributedGradle_Check' (id = 'DistributedTest')
accordingly, and delete the patch script.
*/
changeProject(uuid("DistributedGradle_Check")) {
    params {
        add {
            param("env.GRADLE_ENTERPRISE_ACCESS_KEY", "credentialsJSON:f9ee1ece-2df6-486e-97f4-9bf2767b6cf8")
        }
        add {
            param("gradle.cache.remote.password", "credentialsJSON:7b004bb5-3736-4116-854a-73f2acf39b8a")
        }
        add {
            param("gradle.cache.remote.username", "teamcity")
        }
        add {
            param("gradle.cache.remote.url", "credentialsJSON:e5dbdfce-68c9-4022-a084-155bd822e791")
        }
    }
}
